apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:1nSFgiZYH4A6p5TEAwr63fJ2Fjlc6ua0kI0iWvBnXgTynYGnyjnuNTZlq8GiOHdKcKaN8DuyYXI=,iv:BgnKJWALneZNGTjUqopuGy3LLyCndneLi2TUaqRcTXo=,tag:kNN+jgzbr17fef/cQwTwgw==,type:str]
kind: Secret
metadata:
    name: env
    namespace: renovate
sops:
    age:
        - recipient: age1jrp5h2mwujrjw0vqgvqeqah33s8mfuh93dqz2vrj3hhdtku5qcfq6gkg35
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVDVudzkza3BsTTNSMEVi
            bCtBSnVVbTJGOWtmMVdlOG5URFVFLy92L3k0CndJeXp5RjA5VGVNaTJhRHVCNkZm
            WVF5Y1JJLzhzZHhtTzkxM2VpSGpSNEEKLS0tIGU4U29mQXFXL1l6UG81c3FOUDhk
            ckY1aHFBczI1Y3dodDg0TXBHcllXV2MKg8kOGFw+kkGe+EfdmGUqAgobkv415hdO
            pGAQgZ5puawWQQVPUv+Sd/eHAaiT8afB1b2BtzE8SKGbaNRyUJWl5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T09:42:25Z"
    mac: ENC[AES256_GCM,data:caHuhBY2kUGQpv+g++NxKHIOJ5FzFr001jjugna1LyPiIFMzWIT7QiIWaefiNrY5bYQmwgjfPjZc4Zgoo7TuReUVGmfIYtOHsx79oz+vQb767tErx3zLon+Db0k6VBfnJxk8e5UOEZ8xz76R2wZzlP47WZT++nQ5xXWw/SDdkxE=,iv:CVYhOX59zS0jssZec8zkGgNlNm07i6OLxI+3tjFsOpU=,tag:U2GjwQO+G6+7z4b4ytl6uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
