apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:qSo8FLQ4CGuwW7KBGWUWJse7Ml1QN8nChKRkMl8oNJVDbcEkwUqPNHiEljcRycuoLKu9bZllL4ThzNE9vFI3xFdBW9CFgQRuXCiw+jP3FAEGEgR5aU2OpIrnMpyCHpcgvtZNfEJJVkopAZX3RNUF5wUr+EK7fbrVOqeBg2DhzYjaUzVkW3UHjYXpbEZbj0Gxh2z1GZwvt7go//emmzIK8iC2sQwD2ENo7Ii8S0csDNucHB2arIJDVaEaqgHIY6LhzYOfaRZYJXdChxMeFYtZWe7Uyld2TaVG97q4AJM7crXT2ZSafodi2TKEgJY=,iv:yvnzHCA9cbwMabMIT+g2JvSx46sKADYzzip0vjicDZ8=,tag:8WBntYYYXxNShDS2RV/wIQ==,type:str]
kind: Secret
metadata:
    name: cloudflared-credentials
sops:
    age:
        - recipient: age1jrp5h2mwujrjw0vqgvqeqah33s8mfuh93dqz2vrj3hhdtku5qcfq6gkg35
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWk01YWx4RHJhMWU5cCt2
            U0E2QSs5amlmTmxjUFNKUTFYcVFWNjlUU0hzCkhMRHdYQXRSM1lncGZTMVA0emRH
            UFBqbFN5N0ZuYzhJSGxFcGE1Rk0rbVEKLS0tIHUzejVkeUlERkkzV3ZhbmNKbGR6
            OWprRmczVkJJa1RDYzBtejFISEFpeG8KbxHkI2d7eLEh9LlWZP99zkXMA1CsMyzg
            2XkDzaALtAaSrirnPjjCg8gzjEvcz4X6vlx+EnVEVfcuvshUq8OENA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T16:30:21Z"
    mac: ENC[AES256_GCM,data:yDOlIwFQA2AgC/aOfeZS44+HKSUruf9qhDG4FHq66jXqPKBTi2ir9rCE0tcXrI+T3qVMn0M6ShkoI+Bue4hNRqye3h7awYHs0mpg/9ggPFWv3QX8+DC1pCr0cQnV3DArNsHQlLI4D0B0WBJCumayiIvFKTO6MAjyxuj672BhZrI=,iv:jX3RR3PTrRjHk9PmkNUtogoddUu7qyMfXNA+pUBbPkA=,tag:cVTVdGUKo7E5agYKmkQmhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
